'use client'
import type { Metadata } from "next";
import localFont from "next/font/local";
import { ChakraProvider } from '@chakra-ui/react'
//import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

//I believe this should be removed, left here because I was not sure if it is needed later - Rei
/**export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};**/

//Attached the ChakraProvider tag to the Rootlayout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ChakraProvider>{children}</ChakraProvider>
      </body>
    </html>
  );
}
