"use client"
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Providers } from "./providers";
import "./globals.css";
import Footer from "../components/footer";
import Navbar from "../components/navbar";
import { Caveat, Mansalva, Handlee } from "next/font/google";

const caveat = Caveat({
  variable: "--font-caveat",
  subsets: ["latin"]
});

const mansalva = Mansalva({
  variable: "--font-mansalva",
  weight: "400",
  subsets: ["latin"]
});

const handlee = Handlee({
  variable: "--font-handlee",
  weight: "400",
  subsets: ["latin"]
})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


/** //Conflicts with Chakra"s "use client"
  export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};**/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${caveat.variable} ${handlee.variable}`} lang="en">
      <body>
          <Providers>
            <Navbar/>
            {children}
            <Footer/>
          </Providers>
      </body>
    </html>
  );
}
